# Generated by Django 3.2.5 on 2021-08-22 03:08

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('img', models.CharField(max_length=200)),
                ('tran_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('douban_rate', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('publish_date', models.CharField(max_length=200)),
                ('movie_time', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('main_actor', models.CharField(max_length=200)),
                ('download_url', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('lookuser', models.ManyToManyField(blank=True, related_name='userlike_movie', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
                'db_table': 'Movie',
            },
        ),
    ]
